name: infoplus
description: Aplicativo Flutter InfoPlus - offline-first
version: 2.0.0+2

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.29.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  flutter_launcher_icons: ^0.13.1

  # Gerenciamento de estado
  provider: ^6.1.4

  # Geração de código
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # HTTP e conectividade
  http: ^1.2.1
  connectivity_plus: ^6.1.4

  # Armazenamento local
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2

  # Banco local com Drift
  drift: ^2.15.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.5.0
  firebase_messaging: ^15.2.5

  # Variáveis de ambiente
  flutter_dotenv: ^5.1.0

  # Internacionalização e ícones
  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Permissões
  permission_handler: ^12.0.0+1

  # Utilitários
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  drift_dev: ^2.15.0
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  test: ^1.25.15

flutter:
  uses-material-design: true
  
  # Configuração de assets
  assets:
    - assets/icons/payments/emola.png
    - assets/icons/payments/mpesa.png
    - assets/icons/app/app_icon.png

  # Configuração de fonts (mantido caso precise)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700

# Configuração dos ícones do aplicativo
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app/app_icon.png"
  min_sdk_android: 23
