name: CI Flutter ─ Build APK Debug Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      JAVA_VERSION: '17'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: stable
          cache: true

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: "34.0.0"

      - name: Instalar build-tools com AAPT2
        run: sdkmanager "build-tools;34.0.0"

      - name: Instalar dependências
        run: flutter pub get

      - name: Gerar código (build_runner + drift)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK Debug via Gradle
        run: |
          flutter clean
          ./gradlew assembleDebug

      - name: Verificar APK gerado na pasta customizada
        run: find apk_output/ -name "*.apk"

      - name: Upload do APK Debug gerado na pasta customizada
        uses: actions/upload-artifact@v4
        with:
          name: infoplus-debug-apk
          path: apk_output/debug.apk
          retention-days: 7